### PR TITLE
Simplify utulity to fetch attributes

### LINKED ISSUE #163: p11prov_fetch_attributes may return bad error code/data on failure
**Describe the bug**
If the attribute requested is sensitive or otherwise and is "required" the function may return short w/o processing all data and with the wrong error code (CKR_HOST_MEMORY)

**To Reproduce**
N/A

**Expected behavior**
All available attributes should be processed and returned even on error
P11PROV_debug statements (or even P11PROV_raise for required ones) are emitted so that there is a log of which attributes were required/requested and were not returned

**Operating environment (please complete the following information):**
N/A

**Token and application used (please complete the following information):**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by simo5**
REduce the size and reuse the CK_ATTRIBUTE structure within fetch_attrs to further simplify copying data between attribute storages when needed.

Also fix some checks in the derive key functions that I found wrong while refactoring.

Fixes #163

### CODE REVIEW

File: src/exchange.c [hunk 1]
```diff
@@ -266,9 +260,14 @@ static int p11prov_ecdh_derive(void *ctx, unsigned char *secret,
 
     /* complete key template */
     if (ecdhctx->kdf_outlen) {
-        key_size = ecdhctx->kdf_outlen;
+        if (ecdhctx->kdf_outlen < outlen) {
+            key_size = ecdhctx->kdf_outlen;
+        }
```
Comment (Jakuje) [inline src/exchange.c:265]: with this change, the `key_size` is kept on 0 in case of `ecdhctx->kdf_outlen >= outlen` instead of an error that was raised previously if I see right, which does not look correct.

Comment (simo5) [reply src/exchange.c:265]: Uggh good catch.
I am not completely focused today, but I believe I should have fixed this now

**Review by Jakuje — APPROVED** [review]
