### PR TITLE
Set the raw point for ECDH public data params

### LINKED ISSUE #416: ECDH Params public data should be raw format by default, not DER
**Describe the bug**
When the pPublicData parameter is filled we source CKA_EC_POINT which is the DER encoded format of the EC public point, however the spec says:

```
pPublicData       pointer to other party’s EC public key value. For short Weierstrass
                  EC keys: a token MUST be able to accept this value encoded as a raw
                  octet string (as per section A.5.2 of [ANSI X9.62]).  A token MAY, 
                  in addition, support accepting this value as a DER-encoded ECPoint 
                  (as per section E.6 of [ANSI X9.62]) i.e. the same as a CKA_EC_POINT
                  encoding.  The calling application is responsible for converting the
                  offered public key to the compressed or uncompressed forms of these
                  encodings if the token does not support the offered form.
```

Both softhsm and NSS autodetect and convert as needed, but kryoptic is failing ECDH tests because of this.

**To Reproduce**
Enable ECDH test for kryoptic

**Expected behavior**
We should provide the format that the spec lists as MUST for this parameter, not what is listed as MAY, as some tokens MAY not support it.

**Operating environment (please complete the following information):**
 - OS: Fedora
 - Version: rawhide

**Token and application used (please complete the following information):**
 - Device: Kryoptic
 - PKCS11 Driver version: main tree
 - Application: Pkcs11-provider's CI
 - Version: main tree

**Additional context**
Related Kryoptic bug at https://github.com/latchset/kryoptic/issues/66

### PR DESCRIPTION
**Pull request by simo5**
#### Description

Changes the format of the point passed into ECDH Params

Enables Kryoptic ECDH test, which now passes.

Fixes #416 

#### Checklist

- [x] Code modified for feature
- [x] Test suite updated with functionality tests
- [x] Test suite updated with negative tests
- ~[ ] Documentation updated~

#### Reviewer's checklist:

- [x] Any issues marked for closing are addressed
- [x] There is a test suite reasonably covering new functionality or modifications
- ~[ ] This feature/change has adequate documentation added~
- [x] Code conform to coding style that today cannot yet be enforced via the check style test
- [x] Commits have short titles and sensible commit messages
- [x] Coverity Scan has run if needed (code PR) and no new defects were found

### CODE REVIEW

File: src/objects.c [hunk 1]
```diff
@@ -2175,6 +2175,65 @@ int p11prov_obj_get_ec_public_x_y(P11PROV_OBJ *obj, CK_ATTRIBUTE **pub_x,
...
+        P11PROV_raise(key->ctx, CKR_GENERAL_ERROR, "Invalid Object Class");
+        return RET_OSSL_ERR;
+    }
+
+    pub_key = p11prov_obj_get_attr(key, CKA_P11PROV_PUB_KEY);
+    if (!pub_key) {
+        CK_ATTRIBUTE *ec_point;
+
+        ec_point = p11prov_obj_get_attr(key, CKA_EC_POINT);
+        if (ec_point) {
```
Comment (Jakuje) [inline src/objects.c:2201]: Would not be nicer to reverse this condition to avoid nesting the whole processing below?

**Review by Jakuje — APPROVED** [review]
otherwise lgtm

File: src/objects.c (hunk 1 above)
Comment (simo5) [reply src/objects.c:2201]: Maybe, but given this works and it is not terribly ugly, I'll take your LGTM and just merge as is :)
