### PR TITLE
Retry store_fetch with login if nothing found

### LINKED ISSUE #196: Fails to work with HSM (RSA OAEP)
**Describe the bug**

Fails to either encrypt or decrypt.

**To Reproduce**

Encryption (with provider):
```
$ env | grep MODULE
PKCS11_PROVIDER_MODULE=/usr/local/lib/yubihsm_pkcs11.dylib
YUBIHSM_PKCS11_MODULE=/usr/local/lib/pkcs11/yubihsm_pkcs11.dylib
$ echo $MODULE
/usr/local/lib/yubihsm_pkcs11.dylib
$ cmp $MODULE $YUBIHSM_PKCS11_MODULE 
$ 
$ openssl pkeyutl  -encrypt -pubin -inkey "pkcs11:model=YubiHSM;token=YubiHSM;id=%04%02;object=RSA-OAEP;type=public" -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha384 -pkeyopt rsa_mgf1_md:sha384 -in /tmp/key.bin -out /tmp/key.enc
Could not read public key from pkcs11:model=YubiHSM;token=YubiHSM;id=%04%02;object=RSA-OAEP;type=public
pkeyutl: Error initializing context
$
```
Encryption failed - needed to prompt for the PIN, but it didn't.

For decryption (with provider):
```
$ openssl pkeyutl  -decrypt -inkey "pkcs11:model=YubiHSM;token=YubiHSM;id=%04%02;object=RSA-OAEP;type=private" -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha384 -pkeyopt rsa_mgf1_md:sha384 -in /tmp/key.enc -out /tmp/key.dec
Enter pass phrase for PKCS#11 Token (Slot 0 - YubiHSM Connector 0.0.0.0):
Segmentation fault: 11
$ ll /tmp/key.dec
-rw-r--r--  1 ur20980  wheel  32 Feb 14 10:23 /tmp/key.dec
$ cmp /tmp/key.bin /tmp/key.dec
$
```
Appears to have decrypted correctly before crashing OpenSSL. Observed crash:
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [15524]

VM Region Info: 0 is not in any region.  Bytes before following region: 4307480576
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100bef000-100c6f000    [  512K] r-x/r-x SM=COW  ...xec/*/openssl

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_pthread.dylib       	    0x7ff813668f63 pthread_rwlock_rdlock + 0
1   libcrypto.3.dylib             	       0x1012e434f CRYPTO_THREAD_read_lock + 9
2   libcrypto.3.dylib             	       0x10130662b ossl_method_store_cache_get + 59
3   libcrypto.3.dylib             	       0x1012b8aa1 inner_evp_generic_fetch + 366
4   libcrypto.3.dylib             	       0x1012b8912 evp_generic_fetch + 65
5   libcrypto.3.dylib             	       0x1012b6307 evp_cipher_init_internal + 1389
6   libcrypto.3.dylib             	       0x1012b709d EVP_EncryptInit_ex + 27
7   libyubihsm.2.4.0.dylib        	       0x100e4eeba aes_encrypt_ex + 58
8   libyubihsm.2.4.0.dylib        	       0x100e508c2 send_encrypted_msg + 1218
9   libyubihsm.2.4.0.dylib        	       0x100e50259 yh_send_secure_msg + 89
10  libyubihsm.2.4.0.dylib        	       0x100e590ab yh_util_close_session + 107
11  yubihsm_pkcs11.dylib          	       0x100f29264 C_CloseSession + 372
12  pkcs11.dylib                  	       0x100e8ee77 p11prov_CloseSession + 87
13  pkcs11.dylib                  	       0x100e9b242 session_free + 194
14  pkcs11.dylib                  	       0x100e9934e p11prov_free_slots + 366
15  pkcs11.dylib                  	       0x100e9796b p11prov_ctx_free + 187
16  libcrypto.3.dylib             	       0x1012e15ff ossl_provider_free + 61
17  libcrypto.3.dylib             	       0x1013466ac OPENSSL_sk_pop_free + 45
18  libcrypto.3.dylib             	       0x1012e2e02 provider_store_free + 63
19  libcrypto.3.dylib             	       0x1012d91d6 CRYPTO_free_ex_data + 326
20  libcrypto.3.dylib             	       0x1012d66d6 context_deinit + 98
21  libcrypto.3.dylib             	       0x1012d6667 ossl_lib_ctx_default_deinit + 16
22  libcrypto.3.dylib             	       0x1012d95ca OPENSSL_cleanup + 200
23  libsystem_c.dylib             	    0x7ff813562c26 __cxa_finalize_ranges + 416
24  libsystem_c.dylib             	    0x7ff813562a39 exit + 35
25  openssl                       	       0x100c131bb main + 594
26  dyld                          	    0x7ff813339310 start + 2432
```

**Expected behavior**

For encryption (showing with the engine):
```
$ openssl pkeyutl -engine pkcs11 -keyform engine -encrypt -pubin -inkey "pkcs11:model=YubiHSM;token=YubiHSM;id=%04%02;object=RSA-OAEP;type=public" -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha384 -pkeyopt rsa_mgf1_md:sha384 -in /tmp/key.bin -out /tmp/key.enc
Engine "pkcs11" set.
Enter PKCS#11 token PIN for YubiHSM:
$
$ ll /tmp/key.enc
-rw-r--r--  1 ur20980  wheel  384 Feb 14 10:21 /tmp/key.enc
$ 
```

For decryption (showing with the engine):
```
$ openssl pkeyutl -engine pkcs11 -keyform engine -decrypt -inkey "pkcs11:model=YubiHSM;token=YubiHSM;id=%04%02;object=RSA-OAEP;type=private" -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha384 -pkeyopt rsa_mgf1_md:sha384 -in /tmp/key.enc -out /tmp/key.dec
Engine "pkcs11" set.
Enter PKCS#11 token PIN for YubiHSM:
$ cmp /tmp/key.bin /tmp/key.dec
$ 
```

**Operating environment (please complete the following information):**
 - OS: MacOS Ventura
 - Version: 13.2.1

**Token and application used (please complete the following information):**
 - Device: YubiHSM
 - PKCS11 Driver version: YubiHSM-2.4.0
 - Application: OpenSSL
 - Version: 3.0.8

**Additional context**

Works with engine, partially works for decryption with HSM when invoked manually. Adding or removing `object=RSA_OAEP;` to the key URI seems to have no effect, probably better to remove it.

```
$ yhsm2-rsa-encr-prov 
YUBIHSM_PKCS11_CONF = "/Users/ur20980/yubihsm_pkcs11.conf"
YUBIHSM_PKCS11_MODULE = "/usr/local/lib/pkcs11/yubihsm_pkcs11.dylib"


Testing pkcs11 engine (libp11) with YubiHSM

Generate a random data file (1000 bytes), Base64-encoded...
openssl rand -engine rdrand -base64 -out /tmp/derive.1367.text 1000
Engine "rdrand" set.

Engine "rdrand" set.
Engine "rdrand" set.
Generated
  key: 47d3b66087235de5dd0680bba9a64a947e7589aa31b4f8d4eed73201cb4347ba
  iv:  3fbc1b3c023109e4e077e36e2d7baca3

Encrypt file /tmp/derive.1367.text with this key and IV...
openssl enc -aes-256-cfb -a -e -in /tmp/derive.1367.text -out /tmp/derive.1367.text.enc -K 47d3b66087235de5dd0680bba9a64a947e7589aa31b4f8d4eed73201cb4347ba -iv 3fbc1b3c023109e4e077e36e2d7baca3

Encrypting this random symmetric key to token RSA KEY MAN key...
echo 47d3b66087235de5dd0680bba9a64a947e7589aa31b4f8d4eed73201cb4347ba | xxd -r -p -c 200 | openssl pkeyutl -engine pkcs11 -keyform engine -encrypt -pubin -inkey "pkcs11:model=YubiHSM;token=YubiHSM;id=%04%02;object=RSA-OAEP;type=public" -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha384 -pkeyopt rsa_mgf1_md:sha384 -out /tmp/derive.1367.key.enc
Engine "pkcs11" set.
Enter PKCS#11 token PIN for YubiHSM:

encrypted key:
4a3d7d5870e683fc580814117507a2fb09eba5e34060d57dc00e9ace540a8c424638f1ab9633e21ec39349e39588efb8857ef0defb36cffb16eebc619278de4bdbd64e3d075d39dee1c137256df1d779e70d365ccb16fab604d73f0745a60f15a6c95e9a2e7dc872d0a61b088bd9eb2a2ee9120c603e5c55f66ec9f02e3f45a01706be69131e0b3deb3cd823ed46a79633dc06d11eee139b56aad37672144431f7109ad13f0c0b09d8a22478e58db3e850199bbe2751f0a0e2824094b1ae6df63c07417e6846e7e7
5e54632acb1ae0007a0af1a75d1e130cf2246eae3d255db903862422a76f844e7962412f34d9c04eb8b4a9bbfb64c50004fa0b7697b3f1360fe21329d14f45996ab18f7f03e9025d53f8242813a7376d1f29dacbd7af31fc2eb534a261023a110d7d1387e4415f986e6b683453cb11ebaa4d414397a517ba03673d3cf1e5804d73e9822afb41a03034fa7f051b9141be563424c74e181228a9c2b2695d76160b4e2e49ad42909be7527883c0e43a504da7786d211a865c16

Decrypting the symmetric key on the token...
openssl pkeyutl -engine pkcs11 -keyform engine -decrypt -inkey "pkcs11:model=YubiHSM;token=YubiHSM;id=%04%02;type=private" -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha384 -pkeyopt rsa_mgf1_md:sha384 -in /tmp/derive.1367.key.enc | xxd -p -c 200
Engine "pkcs11" set.
Enter PKCS#11 token PIN for YubiHSM:

Decrypt file /tmp/derive.1367.text.enc with this key and IV...
openssl enc -aes-256-cfb -a -d -in /tmp/derive.1367.text.enc -out /tmp/derive.1367.text.dec -K 47d3b66087235de5dd0680bba9a64a947e7589aa31b4f8d4eed73201cb4347ba -iv 3fbc1b3c023109e4e077e36e2d7baca3

KEY1="47d3b66087235de5dd0680bba9a64a947e7589aa31b4f8d4eed73201cb4347ba"
KEY2="47d3b66087235de5dd0680bba9a64a947e7589aa31b4f8d4eed73201cb4347ba"

Original and decrypted keys  match

Original and decrypted files match


Cleaning up...


$ 
```

### PR DESCRIPTION
**Pull request by simo5**
This is to account for the case where HSMs may require login even for public objects. They will return no objects at all unless there is a login session.

If a user is sure their token always allow public objects to be retrieved w/o PIN there is a tunable that can be set to avoid the fallback annoyance when the pkcs11 uri is imply not matching a public key correctly.

Fixes #196

### CODE REVIEW

File: src/provider.c [hunk 1]
```diff
@@ -1083,6 +1091,9 @@ int OSSL_provider_init(const OSSL_CORE_HANDLE *handle, const OSSL_DISPATCH *in,
     core_params[3] =
         OSSL_PARAM_construct_utf8_ptr(P11PROV_PKCS11_MODULE_ALLOW_EXPORT,
                                       &allow_export, sizeof(allow_export));
+    core_params[3] =
+        OSSL_PARAM_construct_utf8_ptr(P11PROV_PKCS11_MODULE_LOGIN_BEHAVIOR,
+                                      &login_behavior, sizeof(login_behavior));
     core_params[4] = OSSL_PARAM_construct_end();
```
Comment (Jakuje) [inline src/provider.c:1097]:
```suggestion
    core_params[4] =
        OSSL_PARAM_construct_utf8_ptr(P11PROV_PKCS11_MODULE_LOGIN_BEHAVIOR,
                                      &login_behavior, sizeof(login_behavior));
    core_params[5] = OSSL_PARAM_construct_end();
```

Comment (simo5) [reply src/provider.c:1097]: Nice catch, fixed.

**Review by Jakuje — APPROVED** [review]

File: src/provider.c [hunk 2]
```diff
@@ -330,6 +331,12 @@ int p11prov_ctx_allow_export(P11PROV_CTX *ctx)
     return ctx->allow_export;
 }
 
+int p11prov_ctx_login_behavior(P11PROV_CTX *ctx)
+{
+    P11PROV_debug("login_behavior = %d", ctx->login_behavior);
```
[the remark this answers is not in the document]
Comment (simo5) [reply src/provider.c:336]: It is just debugging, I think it is fine as an int for now.
