### PR TITLE
Fix memory leaks when tokens are missing

### LINKED ISSUE #462: Memory leak in slot.c
**Describe the bug**
On empty slot list whole array P11PROV_SLOTS_CTX::slots is leaked. Also
due to C_GetSlotInfo returning empty slots, memory for them is
allocated, but counter isn't incremented due to `continue` in cycle body thus creating another leak.

Suggested solution is to change P11PROV_SLOTS_CTX::slots from array of
poiners to array of structs to fight the second problem. 
And do not skip
`p11prov_free_slots` when number of present slots is 0 for the first problem.

I have commit with fix on my hands, and ready to present a pull request

### PR DESCRIPTION
**Pull request by simo5**
#### Description

In case we have slots advertized but the driver fails to return information or the token is not present we were leaking memory as the slot is not added to the array and the number of slots is not incremented.

Ensure the slot struct is freed in this case.

Fixes #462 

#### Checklist

- [x] Code modified for feature
- [ ] ~Test suite updated with functionality tests~
- [ ] ~Test suite updated with negative tests~
- [ ] ~Documentation updated~

#### Reviewer's checklist:

- [x] Any issues marked for closing are addressed
- [x] There is a test suite reasonably covering new functionality or modifications
- [ ] This feature/change has adequate documentation added
- [x] Code conform to coding style that today cannot yet be enforced via the check style test
- [x] Commits have short titles and sensible commit messages
- [x] Coverity Scan has run if needed (code PR) and no new defects were found

### CODE REVIEW

File: src/slot.c [hunk 1]
```diff
@@ -187,11 +187,13 @@ CK_RV p11prov_init_slots(P11PROV_CTX *ctx, P11PROV_SLOTS_CTX **slots)
         ret = p11prov_GetSlotInfo(ctx, slotid[i], &slot->slot);
         if (ret != CKR_OK || (slot->slot.flags & CKF_TOKEN_PRESENT) == 0) {
             /* skip slot */
+            OPENSSL_free(slot);
```
Comment (Jakuje) [inline src/slot.c:190]: at this moment, the `slot` is already stored in the `sctx->slots[sctx->num]`. Even though the `sctx->num` is incremented only at the end of this cycle, its possible that this could cause use after free. Would it be safer to move the assignment from lime 185 to the end of the cycle too?

Comment (Jakuje) [reply src/slot.c:190]: The remaining `goto done` conditions should also free this memory, shouldn't it?

Comment (simo5) [reply src/slot.c:190]: uhmm, yeah this requires a little bit more work than I thought, expect a new push

**Review by Jakuje — DISMISSED** [review]

**Comment by DEX1999** [comment]
And what about leak when you allocate `num`, which equals to numbers of slots in system, elements on string 169 and then if `sctx->num == 0` which is equals to number of slots with tokens you just return without freeing.

**Comment by latal-1** [comment]
You still have a leak due to exiting from `p11prov_free_slots` [before](https://github.com/latchset/pkcs11-provider/blob/e0640320367ad5a2866bf4d77963bd5040d40d1d/src/slot.c#L351) [free](https://github.com/latchset/pkcs11-provider/blob/e0640320367ad5a2866bf4d77963bd5040d40d1d/src/slot.c#L369)

File: src/slot.c [hunk 2]
```diff
@@ -182,19 +182,23 @@ CK_RV p11prov_init_slots(P11PROV_CTX *ctx, P11PROV_SLOTS_CTX **slots)
...
         }
         ret = p11prov_GetTokenInfo(ctx, slotid[i], &slot->token);
         if (ret) {
             /* skip slot */
+            OPENSSL_free(slot);
             continue;
         }
 
+        sctx->slots[sctx->num] = slot;
+        sctx->num++;
```
[the remark this answers is not in the document]
Comment (simo5) [reply src/slot.c:200]: I prefer not.

**Comment by simo5** [comment]
> > And what about leak when you allocate `num` elements on string 169, which equals to numbers of slots in system, and then if `sctx->num == 0`, which is equals to number of slots with tokens, you just return without freeing.
> 
> It is a corner case not worth optimizing for IMHO. Especially because I have a plan, in the future, to keep slots around that do not have token present as we have an interest in supporting token insertion in the future.

I misread the comment, sorry, pushed another change that drops the early return in the freeing function.

**Review by Jakuje — APPROVED** [review]
lgtm

**Comment by simo5** [comment]
ty!
